--- #MongoDB deployment
# The blueprint of our MongoExpress deployment in k8s using the secrets

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-deployment
  labels:
    app: mongoexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - name: mongoexpress
        image: mongo-express:1.0
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongoexpress-configmap
              key: database_url


--- #MongoDB service
#The blueprint of our MongoExpress external service in k8s cluster which will allow the external requests

apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  selector:
    app: mongoexpress
  type: NodePort  #NodePort allows the nginx-ingress-controller to work efficiently on MacOS M1
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000