apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: pg-namespace
type: kubernetes.io/tls
data:
  tls.crt: (fill with your base64 encoded certificate)
  tls.key: (fill with your base64 encoded private key)